use_frameworks!

target 'ProatomicNotificationExtension_Example' do
    platform :ios, '11.0'
  pod 'ProatomicNotificationExtension', :path => '../'

  target 'ProatomicNotificationExtension_Tests' do
    inherit! :search_paths

    #pod 'FBSnapshotTestCase'
  end
end
